### ISSUE TITLE
Bug in data loading

### ISSUE THREAD

**Issue by intr** [JanisE/who_is_who_in_socionics#4]
I am no longer able to load data since migrating to the new group "2 tipi satiekas".
I get an error message:
"Could not find a Facebook poll in the active tab to load from."
Even when the link is correct, the poll is open and fully expanded.

https://youtu.be/pchsO-TcAhg

Google Chrome | 83.0.4103.106 (Official Build) (64-bit) (cohort: 83_61_Win)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | Windows 10 OS Version 1903 (Build 18362.900)
JavaScript | V8 8.3.110.13
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

**Comment by JanisE** [comment]
I've added support for single-option polls (with radio buttons as opposed to check-boxes) and submitted the fix to browsers' add-on stores.

Firefox published it immediately, so it's already available.
Chrome's review process may take up to a few weeks.

**Comment by JanisE** [comment]
All right, Chrome has published the new version, too.

**Comment by intr** [comment]
I confirm that data loading is working now with single-option radio button polls in Chrome. Thank you for the quick fix.
